### ISSUE TITLE
Helpers on event matching 

### ISSUE THREAD

**Issue by bertrandlalo** [timeflux/timeflux#20]
The event matching algorithm is common enough to deserve its own helper. 
It is already used in: 
- gate, 
- accumulate
- epochs
https://github.com/timeflux/timeflux/blob/b1623086ce893b343ec5752e93cfa383e13f71c8/timeflux/nodes/gate.py#L46

**Comment by mesca** [comment]
Implemented in 7461eb84d86ba62a2a252b9d50e3f905b216c44d.

**Comment by mesca** [comment]
@bertrandlalo Should I let you update the `accumulate` and `gate` nodes?
