### ISSUE TITLE
Set do not ensure index is montonic

### ISSUE THREAD

**Issue by bertrandlalo** [timeflux/timeflux#35]
https://github.com/timeflux/timeflux/blob/d22423d17e6e2db06535f2b8fff44f79b893f12e/timeflux/core/io.py#L26

If rate is 0, then it's assumed to be 1. It's very likely that we end up with not monotonic index. 
I suggest: 
- either to warn the user when rate = 0 (or even prevent it?)
- either keep in mind last timestamp (`_updated`) and warn when `start<_updated` and set `start = max(start, _updated).`

**Comment by mesca** [comment]
I don't recommend using `set()` to automatically construct the timestamps anymore, as the registry will soon be deprecated. See [this](https://github.com/timeflux/timeflux/issues/32#issuecomment-569836398) for details.

**Comment by mesca** [comment]
I'm closing this issue as it is tracked in #32.
