### ISSUE TITLE
Make it easier to create nodes that handle ports independently

### ISSUE THREAD

**Issue by jonathanjfshaw** [timeflux/timeflux#50]
There's a lot of use cases for nodes that apply the same logic to every port, with each port independent of the others.

The built-in _expression_ node does this, but many others like the _apply_ node don't. Let's provide an convenient and standardised way to handle this.

It seems to me there's a simple solution: - we could alter the default update method in the Node class to something like this:

```
    def update(self):
        inPorts_ready = [[name, suffix, port] for name, suffix, port in self.iterate('i*') if port.ready()]
        for name, suffix, inPort in inPorts_ready:
            outPort = getattr(self, "o" + suffix)
            self.updatePort(suffix, inPort, outPort)
```

Then nodes don't have to implement an update method, they can just implement updatePort.

**Comment by jonathanjfshaw** [comment]
I'm happy to do a PR if you like the idea.

**Comment by mesca** [comment]
I want the core `Node` class to be as simple and lightweight as possible. The logic is: when you create a node, there is only one mandatory method to implement (`update()`) and one optional method (`terminate()`). I understand your point, but IMHO this brings more confusion. I am closing this issue for now, but if you fill this is a recurrent need, do not hesitate to reopen. Maybe a simple helper with a callback argument could do the trick.

**Comment by jonathanjfshaw** [comment]
No problem. The motivation for my idea was to reuse nodes within a graph, but actually that often doesn't work anyway because it Timeflux thinks its a circular dependency and rejects the graph. Reusing nodes may be a bad idea anyway.
