### ISSUE TITLE
Interpolate node should set rate in meta if it has got meta from parameter

### ISSUE THREAD

**Issue by jonathanjfshaw** [timeflux/timeflux#55]
Nodes that are downstream of an interpolate node should be able to receive via the meta the rate that has been enforced onto the data by Interpolate.

**Comment by mesca** [comment]
Thanks!

**Comment by jonathanjfshaw** [comment]
Did you mean to close? Looks like the commit includes test changes but not the fix.

**Comment by mesca** [comment]
Oops! Forgot to push a file.

**Comment by jonathanjfshaw** [comment]
I think the fix was not quite right, it would overwrite the rate in the meta with "None" if the rate came from the meta. PR provided.
