### ISSUE TITLE
EDF, BDF+ etc support

### ISSUE THREAD

**Issue by kkavod** [timeflux/timeflux#72]
Hello I just tried out Timeflux with FreeEEG32 headset — it is really amazing! I heard there's work going on regarding an EDF or BDF etc nodes, that is great. Is the current recommended solution to implement a custom plugin to save in those formats?

**Comment by mesca** [comment]
The current preferred way for recording data is to use the HDF5 plugin. It can handle arbitrary data streams and metadata, and has a 64 bit precision.
The EDF/BDF file formats are much more constrained.
I was rather thinking of writing a small helper to convert from HDF5 to BDF after the acquisition. Would that work for you?

**Comment by kkavod** [comment]
Yes, absolutely. I was curious what HDF5 nodes are used for and now I get it. Thank you Pierre!

**Comment by mesca** [comment]
I'm keeping this issue open until the code is ready.

**Comment by mesca** [comment]
We now have a HDF5 to BDF+ converter: https://github.com/timeflux/timeflux/commit/cf69881ee4b6c388d026408bce6a2c8ab2312eec
It can be called either from the command line (`python -m timeflux.helpers.bdf <path>`) or from a [post hook](https://doc.timeflux.io/en/stable/usage/getting_started.html#environment).
Let me know if you have further question.
