### ISSUE TITLE
Recommended way to debug new nodes?

### ISSUE THREAD

**Issue by juliencarponcy** [timeflux/timeflux#78]
Hi, 

Thank you for your work, the framework looks great. I'm trying to see whether i can adopt it by starting to code simple nodes.
One node I am starting to build is just a processor of string contained in LSL Makers. So I use the lsl node as a receiver and connect it to my custom node. 

However, figuring out the ins and outs of your code in order to build correctly structured node is not so straightforward to me, so that I need to pause script execution at some points in its execution to better understand what is happening and what i am doing wrong.

I find already quite hard to debug scripts which are not standalone methods or function, I tried pdb.set_trace(), but obviously your scheduler did not like it and crashed the framework probably because I was preventing it to execute scheduled tasks.

Do you have good ways to debug while building your nodes? I am working in VScode, so if you do to, launch.json example files used to debug this type of task would be great !

Thanks very much,

Julien

**Comment by mesca** [comment]
Hi Julien,

You could simply use the [-d](https://doc.timeflux.io/en/stable/usage/getting_started.html#command-line-options) flag when launching Timeflux and use the self.logger.debug() method in your code.

Does that help?

**Comment by juliencarponcy** [comment]
Thanks Pierre,

Yes it does, as just a cleaner way of print statements, but I guess due to the framework execution and especially the scheduler, one can not expect to be able to "pause" the execution of a script in a particular line of a node with access to the local variables available to that module at that particular time?

But yeah debugging printing/logging a few things will do, as I do now, as i guess there is no easy work-around this.

Thanks very much again. 

I will soon probably open a new issue relative to the best pattern of usage of timeflux for a particular case (LSL events containing serialized dicts and the best pattern to process them to later gate/trigger signal processing). 

You can close this one if there is not much more to add.
