### ISSUE TITLE
[Repost from demos repo] predict.py node / probability accumulation : Usage clarifications

### ISSUE THREAD

**Issue by juliencarponcy** [timeflux/timeflux#81]
Hi, 

Sorry for the cross-posting, original issue at the following URL

https://github.com/timeflux/demos/issues/12#issue-2402867275

I assumed maybe the core timeflux repo might be more "monitored" for issues, hence my double posting.

Thanks very much in advance and sorry if this wasn't necessary.

Best, 

Julien

**Comment by mesca** [comment]
Closing this as I answered on https://github.com/timeflux/demos/issues/12.
